default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['MYSITE_DATABASE_USER'] %>
  password: <%= ENV['MYSITE_DATABASE_PASSWORD'] %>
  host: <%= ENV['MYSITE_DATABASE_HOST'] %>

development:
  <<: *default
  database: mysite_development

test:
  <<: *default
  database: mysite_test

production:
  <<: *default
  database: mysite_izzg
